name: Daily Vercel Deploy

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Add this line to enable manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Vercel Deploy
      env:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        VERCEL_GET_DEPLOY_DI: ${{ secrets.VERCEL_GET_DEPLOY_DI }}
      run: |
       curl -X GET https://api.vercel.com/v1/integrations/deploy/$VERCEL_PROJECT_ID/$VERCEL_GET_DEPLOY_DI